// Generated by CoffeeScript 1.10.0
(function() {
  var PhysicsObject;

  module.exports = PhysicsObject = (function() {
    PhysicsObject.prototype.xVel = 0;

    PhysicsObject.prototype.yVel = 0;

    function PhysicsObject(x1, y1, mass) {
      this.x = x1;
      this.y = y1;
      this.mass = mass;
      this.lastX = this.x;
      this.lastY = this.y;
      this.displayObj = new createjs.Shape();
      this.displayObj.x = this.x;
      this.displayObj.y = this.y;
    }

    PhysicsObject.prototype.capture = function() {
      this.lastX = this.x;
      return this.lastY = this.y;
    };

    PhysicsObject.prototype.update = function() {
      this.x += this.xVel;
      return this.y += this.yVel;
    };

    PhysicsObject.prototype.addEventHandler = function(event, handler) {
      return this.displayObj.addEventListener(event, handler);
    };

    PhysicsObject.prototype.getEnergy = function() {
      return 0.5 * this.mass * ((this.xVel * this.xVel) + (this.yVel * this.yVel));
    };

    PhysicsObject.prototype.draw = function(x, y) {
      this.displayObj.x = x;
      return this.displayObj.y = y;
    };

    return PhysicsObject;

  })();

}).call(this);
