var eCollisionSettings = {
	simulationWidth: 1000,
	simulationHeight: 1000,
	simulationCanvas: "simulation-canvas",
	graphCanvas: "graph-canvas",
	overlayCanvas: "overlay-canvas",
	refreshRate: 60,
	updateRate: 50,
	showVelocities: false,
	enableInterpolation: true,
	maxTraceLength: 30,
	graphScaleX: 1/50,
	graphScaleY: 5,
	graphZoomFactor: 1.25,
	speedConst: 1.0,
	maxParticles: 100,
	minRadius: 5,
	maxRadius: 30,
	errorTime: 5000,
	gridInterval: 50
}