// Generated by CoffeeScript 1.10.0
(function() {
  var Widget;

  module.exports = Widget = (function() {
    function Widget(canvasName) {
      this.canvasName = canvasName;
      this.canvas = $("#" + this.canvasName);
      this.width = this.canvas.width();
      this.height = this.canvas.height();
      this.hidden = false;
      this.stage = new createjs.Stage(this.canvasName);
      this.canvas.attr("width", this.width);
      this.canvas.attr("height", this.height);
    }

    Widget.prototype.init = function() {};

    Widget.prototype.addEventListener = function(event, handler) {
      return this.stage.addEventListener(event, handler);
    };

    Widget.prototype.draw = function(interpolation) {};

    Widget.prototype.restart = function() {};

    Widget.prototype.stop = function() {};

    Widget.prototype.resume = function() {
      return this.paused = false;
    };

    Widget.prototype.pause = function() {
      return this.paused = true;
    };

    Widget.prototype.resize = function(newWidth, newHeight) {
      this.width = newWidth;
      return this.height = newHeight;
    };

    Widget.prototype.show = function() {
      this.hidden = false;
      return this.canvas.fadeIn(200);
    };

    Widget.prototype.hide = function() {
      this.hidden = true;
      return this.canvas.fadeOut(200);
    };

    return Widget;

  })();

}).call(this);
