// Generated by CoffeeScript 1.10.0
(function() {
  var Particle, PhysicsObject, Point2D,
    extend = function(child, parent) { for (var key in parent) { if (hasProp.call(parent, key)) child[key] = parent[key]; } function ctor() { this.constructor = child; } ctor.prototype = parent.prototype; child.prototype = new ctor(); child.__super__ = parent.prototype; return child; },
    hasProp = {}.hasOwnProperty;

  PhysicsObject = require('./physics-object');

  Point2D = require('../math/point-2d');

  module.exports = Particle = (function(superClass) {
    extend(Particle, superClass);

    Particle.prototype.selected = false;

    Particle.prototype.cOR = 1.0;

    Particle.prototype.pastPositions = [];

    Particle.prototype.curPos = 0;

    function Particle(x, y, radius, style, settings) {
      this.radius = radius;
      this.style = style;
      this.settings = settings;
      Particle.__super__.constructor.call(this, x, y, 0);
    }

    Particle.prototype.update = function() {
      this.x += this.xVel * this.settings.global.speedConst;
      return this.y += this.yVel * this.settings.global.speedConst;
    };

    Particle.prototype.copy = function() {
      var p;
      p = new Particle(this.x, this.y, this.radius, this.style, this.settings);
      p.index = this.index;
      p.cOR = this.cOR;
      p.mass = this.mass;
      p.xVel = this.xVel;
      p.yVel = this.yVel;
      return p;
    };

    return Particle;

  })(PhysicsObject);

}).call(this);
