// Generated by CoffeeScript 1.10.0
(function() {
  var Point2D;

  module.exports = Point2D = (function() {
    function Point2D(x, y) {
      this.x = x;
      this.y = y;
    }

    return Point2D;

  })();

}).call(this);
