// Generated by CoffeeScript 1.10.0
(function() {
  var Interpolatable;

  module.exports = Interpolatable = (function() {
    function Interpolatable() {}

    Interpolatable.prototype.interpolate = function(fraction) {};

    return Interpolatable;

  })();

}).call(this);
