// Generated by CoffeeScript 1.10.0
(function() {
  var Renderer;

  module.exports = Renderer = (function() {
    function Renderer() {}

    Renderer.prototype.draw = function(interpolation) {};

    return Renderer;

  })();

}).call(this);
