// Generated by CoffeeScript 2.2.2
var PhysicsObject;

import EventManager from "../events/event-manager.js";

export default PhysicsObject = (function() {
  class PhysicsObject {
    constructor(x, y, mass) {
      this.x = x;
      this.y = y;
      this.mass = mass;
      this.lastX = this.x;
      this.lastY = this.y;
      EventManager.eventify(this);
    }

    capture() {
      this.lastX = this.x;
      return this.lastY = this.y;
    }

    update() {
      this.x += this.xVel;
      return this.y += this.yVel;
    }

    getEnergy() {
      return 0.5 * this.mass * ((this.xVel * this.xVel) + (this.yVel * this.yVel));
    }

  };

  PhysicsObject.prototype.xVel = 0;

  PhysicsObject.prototype.yVel = 0;

  return PhysicsObject;

}).call(this);
